Page({
  data:{
    value:"",
    swiperOptions:{
      indicatorDots:true,
      autoplay:true,
      interval:3000,
      duration:1000
    },
    navData:[
      {
        text:"云荔爆款",
        icon:"hot",
        color:"#ff0000"
      },
      {
        text:"限时特惠",
        icon:"discount",
        color:"#ff0000"
      },
      {
        text:"文创周边",
        icon:"point-gift",
        color:"#ff0000"
      },
      {
        text:"商品收藏",
        icon:"like",
        color:"#ff0000"
      },
      {
        text:"果树认购",
        icon:"new",
        color:"#ff0000"
      },
      {
        text:"荔枝制品",
        icon:"goods-collect",
        color:"#ff0000"
      },
      {
        text:"荔枝文化",
        icon:"records",
        color:"#ff0000"
      },
      {
        text:"研学旅行",
        icon:"map-marked",
        color:"#ff0000"
      }
    ]
  },
  OnLoad:{
  },
  /** 
  *点击搜索框，获取焦点并跳转页面
  */
  clickSearch(){
    wx.navigateTo({
      url: '/pages/search/search',
    })
  }
})